Add ability to preventDefault
lupas/vue-keypress pull request #3
Opened 2020-03-06 01:23 UTC by anubisthejackle

This PR adds the ability to pass a boolean value to Keypress to run the preventDefault method on the keyup event. This will allow for situations where you want to use this feature on longer pages with the up arrow or down arrow keys without allowing it to scroll.

2020-03-06 08:46 UTC, lupas requested changes
Hey @anubisthejacke

Thanks for the PR! :)

Could you:
- Fix the issues I marked in the PR
- Add the new Prop to the documentation in the Readme?

Thanks a lot!

2020-03-06 08:46 UTC, lupas commented on src/index.vue
> +      type: Bolean,
Could you change this to `Boolean`?

2020-03-06 08:46 UTC, lupas commented on src/index.vue
> +      default: null
This line can & should be deleted.

Boolean types are by default `false` if not defined, so we can omit this line completely.

2020-03-06 13:46 UTC, anubisthejackle commented on src/index.vue
> +      type: Bolean,
Whoops! Missed that typo.

2020-03-06 14:47 UTC, anubisthejackle commented
@lupas Should be good now. Let me know if you need any more changes.

2020-03-10 13:23 UTC, lupas commented
> @lupas Should be good now. Let me know if you need any more changes.

Hey @anubisthejackle 
Sorry, had a very busy last few days.

1. So I tested it today and it did **not** work for me.
E.g. when setting the preventDefault flag and key-code=40, I could still scroll down the page with the down arrow. Did you test your changes yourself? I tested it on Google Chrome.

2. I think we would want to do write it this way anyway:
```js
    emitEvent(event) { 
      if (event.keyCode === this.keyCode || !this.keyCode) {
        if (this.preventDefault) {
            event.preventDefault();
      }
      this.$emit("pressed", event.keyCode);
      }
    }
```
Otherwise we set preventDefault on any button's click, not just the one we want to handle.

Let me know what you think :)

2020-03-11 01:27 UTC, anubisthejackle commented
@lupas You're absolutely right, that's a much better positioning.

To see it stop the scroll, you will need to test the preventDefault on key_down_ because that's when the scroll action happens.

2020-03-11 09:29 UTC, lupas commented
@anubisthejackle 
Awesome, **keydown** did the trick! ;-)

Thanks a lot, this is great!

2020-03-11 09:29 UTC, merged

2020-03-11 09:36 UTC, lupas commented
Published with [v1.2.0](https://github.com/lupas/vue-keypress/releases/tag/v1.2.0)